### cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@60.60.60.16:18080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

### web
server:
  port: 8080
  servlet:
    context-path: /xxl-job-admin

### actuator
management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

### resources
spring:
  application:
    name: xxl-job-admin
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  ### freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

  ### xxl-job, datasource
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://127.0.0.1:5432/xxl_job
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678

    ### datasource-pool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000

  ### xxl-job, email
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    from: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

### mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
  #mybatis.type-aliases-package=com.xxl.job.admin.core.model

### xxl-job, access token
xxl:
  job:
    accessToken:

    ### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
    i18n: zh_CN

    ## xxl-job, triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100

    ### xxl-job, log retention days
    logretentiondays: 30
